export type ScenarioMessage = {
  speaker: 'A' | 'B'
  text: string
  translatedText?: string
  language?: string
  intent: string
  alignment: number
  friction: number
  urgency: number
  trajectory: 'converging' | 'diverging' | 'stable' | 'escalating' | 'de-escalating'
  sentiment: string
  recommendation?: string
  intentShift?: {
    from: string
    to: string
    description: string
    severity: 'low' | 'medium' | 'high'
  }
}

export type Scenario = {
  id: string
  title: string
  description: string
  domain: string
  languageA: string
  languageB: string
  participantA: string
  participantB: string
  messages: ScenarioMessage[]
}

export const scenarios: Scenario[] = [
  {
    id: 'trade-negotiation',
    title: 'Bilateral Trade Negotiation',
    description: 'Two nations negotiate a trade framework. The conversation shifts from cooperative framing to unresolved concern over enforcement mechanisms.',
    domain: 'Government & Diplomacy',
    languageA: 'en',
    languageB: 'fr',
    participantA: 'Ambassador Chen',
    participantB: 'Minister Dubois',
    messages: [
      {
        speaker: 'A',
        text: 'Thank you for joining today. I believe we have a real opportunity to build something lasting here.',
        intent: 'Cooperation',
        alignment: 72,
        friction: 8,
        urgency: 25,
        trajectory: 'converging',
        sentiment: 'optimistic, collaborative',
        recommendation: 'Acknowledge the cooperative tone and build on shared goals.',
      },
      {
        speaker: 'B',
        text: 'Je suis du même avis. Nous devons saisir cette occasion pour renforcer nos liens économiques.',
        translatedText: 'I agree. We must seize this opportunity to strengthen our economic ties.',
        language: 'fr',
        intent: 'Cooperation',
        alignment: 78,
        friction: 6,
        urgency: 22,
        trajectory: 'converging',
        sentiment: 'aligned, constructive',
        recommendation: 'Continue building momentum on areas of agreement.',
      },
      {
        speaker: 'A',
        text: 'Excellent. I would like to propose a framework that reduces tariffs by 15% over three years, with quarterly review checkpoints.',
        intent: 'Proposal',
        alignment: 74,
        friction: 10,
        urgency: 35,
        trajectory: 'stable',
        sentiment: 'measured, specific',
        recommendation: 'Note the specificity — this is a concrete offer. Prepare to discuss enforcement.',
      },
      {
        speaker: 'B',
        text: 'Le principe est intéressant, mais comment garantirons-nous le respect des engagements si les circonstances changent ?',
        translatedText: 'The principle is interesting, but how will we guarantee commitments are honored if circumstances change?',
        language: 'fr',
        intent: 'Unresolved Concern',
        alignment: 55,
        friction: 35,
        urgency: 48,
        trajectory: 'diverging',
        sentiment: 'cautious, probing',
        intentShift: {
          from: 'Proposal',
          to: 'Unresolved Concern',
          description: 'Minister Dubois shifts from cooperative alignment to questioning enforcement — a shift from negotiation to unresolved concern.',
          severity: 'high',
        },
        recommendation: 'Address the enforcement question directly. Acknowledge the concern before proposing safeguards.',
      },
      {
        speaker: 'A',
        text: 'That is a fair question. We could establish an independent arbitration panel with binding authority — would that address your concern?',
        intent: 'Reassurance',
        alignment: 62,
        friction: 22,
        urgency: 40,
        trajectory: 'converging',
        sentiment: 'responsive, problem-solving',
        recommendation: 'Good recovery. Watch for whether the response is accepted or if further concerns emerge.',
      },
      {
        speaker: 'B',
        text: 'Un panel indépendant pourrait fonctionner, à condition que sa composition soit équilibrée et transparente.',
        translatedText: 'An independent panel could work, provided its composition is balanced and transparent.',
        language: 'fr',
        intent: 'Conditional Agreement',
        alignment: 70,
        friction: 15,
        urgency: 35,
        trajectory: 'converging',
        sentiment: 'cautiously optimistic',
        recommendation: 'The conversation is re-converging. Move toward finalizing the panel structure.',
      },
    ],
  },
  {
    id: 'enterprise-sales',
    title: 'Enterprise Sales Call',
    description: 'A sales executive pitches a platform to a skeptical CTO. The conversation shifts from information exchange to resistance over pricing.',
    domain: 'Enterprise',
    languageA: 'en',
    languageB: 'en',
    participantA: 'Sales Executive',
    participantB: 'CTO Reynolds',
    messages: [
      {
        speaker: 'A',
        text: 'Thanks for taking the time, Ms. Reynolds. I want to understand your current infrastructure challenges before showing you anything.',
        intent: 'Information Exchange',
        alignment: 60,
        friction: 10,
        urgency: 30,
        trajectory: 'stable',
        sentiment: 'open, consultative',
        recommendation: 'Strong opening — let the prospect describe their needs first.',
      },
      {
        speaker: 'B',
        text: 'Appreciate that. Our main pain point is scaling our data pipeline without doubling infrastructure costs every quarter.',
        intent: 'Needs Disclosure',
        alignment: 68,
        friction: 8,
        urgency: 45,
        trajectory: 'converging',
        sentiment: 'frank, solution-seeking',
        recommendation: 'Clear pain point stated. Align your pitch to cost-efficient scaling.',
      },
      {
        speaker: 'A',
        text: 'That is exactly what our platform addresses. We have seen clients reduce pipeline costs by 40% within six months.',
        intent: 'Value Proposition',
        alignment: 70,
        friction: 6,
        urgency: 40,
        trajectory: 'converging',
        sentiment: 'confident, relevant',
        recommendation: 'Good alignment. Prepare for pricing discussion.',
      },
      {
        speaker: 'B',
        text: 'Forty percent sounds impressive. But what does this cost? Our budget is already committed for this fiscal year.',
        intent: 'Resistance',
        alignment: 42,
        friction: 45,
        urgency: 55,
        trajectory: 'diverging',
        sentiment: 'guarded, budget-constrained',
        intentShift: {
          from: 'Needs Disclosure',
          to: 'Resistance',
          description: 'CTO Reynolds shifts from sharing needs to raising budget resistance — a shift from openness to friction.',
          severity: 'high',
        },
        recommendation: 'Budget objection detected. Offer phased implementation or pilot to reduce upfront commitment.',
      },
      {
        speaker: 'A',
        text: 'I understand budget cycles. We offer a phased rollout — start with one pipeline at a fixed pilot cost, expand when you see results.',
        intent: 'Objection Handling',
        alignment: 55,
        friction: 28,
        urgency: 48,
        trajectory: 'converging',
        sentiment: 'empathetic, flexible',
        recommendation: 'Good pivot to a low-risk entry point. Watch for whether the resistance softens.',
      },
      {
        speaker: 'B',
        text: 'A pilot is more palatable. Can you send me a one-pager on the pilot structure? I will review it with my team.',
        intent: 'Conditional Interest',
        alignment: 65,
        friction: 18,
        urgency: 40,
        trajectory: 'converging',
        sentiment: 're-engaged, pragmatic',
        recommendation: 'Friction is decreasing. Send the pilot materials promptly and set a follow-up date.',
      },
    ],
  },
  {
    id: 'crisis-dialogue',
    title: 'Crisis Coordination Dialogue',
    description: 'Two agencies coordinate during a developing emergency. The conversation shifts from information sharing to urgent escalation.',
    domain: 'Defense & Security',
    languageA: 'en',
    languageB: 'es',
    participantA: 'Field Coordinator',
    participantB: 'Regional Director',
    messages: [
      {
        speaker: 'A',
        text: 'Director, we have a developing situation in Sector 7. Reports of infrastructure damage and displaced civilians.',
        intent: 'Information Sharing',
        alignment: 65,
        friction: 12,
        urgency: 55,
        trajectory: 'stable',
        sentiment: 'measured, factual',
        recommendation: 'Clear situational report. Await resource authorization.',
      },
      {
        speaker: 'B',
        text: 'Entendido. ¿Cuál es la escala estimada de los desplazamientos? Necesito cifras para activar recursos.',
        translatedText: 'Understood. What is the estimated scale of displacement? I need figures to activate resources.',
        language: 'es',
        intent: 'Information Sharing',
        alignment: 68,
        friction: 10,
        urgency: 60,
        trajectory: 'stable',
        sentiment: 'focused, requesting data',
        recommendation: 'Director is engaged. Provide specific numbers to enable resource activation.',
      },
      {
        speaker: 'A',
        text: 'Current estimate is 2,000 displaced, growing. Two access roads are compromised. We need authorization for emergency transport.',
        intent: 'Resource Request',
        alignment: 60,
        friction: 15,
        urgency: 72,
        trajectory: 'escalating',
        sentiment: 'urgent, specific',
        recommendation: 'Urgency is climbing. Push for immediate authorization.',
      },
      {
        speaker: 'B',
        text: 'Esto es más grave de lo que esperaba. Autorizo transporte de emergencia inmediatamente. ¿Qué más necesitan?',
        translatedText: 'This is more serious than I expected. I am authorizing emergency transport immediately. What else do you need?',
        language: 'es',
        intent: 'Urgent Escalation',
        alignment: 75,
        friction: 8,
        urgency: 88,
        trajectory: 'escalating',
        sentiment: 'decisive, mobilizing',
        intentShift: {
          from: 'Information Sharing',
          to: 'Urgent Escalation',
          description: 'Regional Director escalates from information sharing to urgent mobilization — a shift from assessment to active response.',
          severity: 'high',
        },
        recommendation: 'Authorization granted. Prioritize transport deployment and identify next resource gaps.',
      },
      {
        speaker: 'A',
        text: 'Transport authorized, thank you. We also need medical support at Checkpoint 3 — injuries reported, no medics on site.',
        intent: 'Urgent Escalation',
        alignment: 78,
        friction: 6,
        urgency: 90,
        trajectory: 'escalating',
        sentiment: 'direct, prioritizing',
        recommendation: 'Continue escalating resource requests. Maintain clear priority ordering.',
      },
      {
        speaker: 'B',
        text: 'Desplazando equipo médico al Punto de Control 3. Mantengámonos en contacto cada quince minutos.',
        translatedText: 'Dispatching medical team to Checkpoint 3. Let us stay in contact every fifteen minutes.',
        language: 'es',
        intent: 'Active Coordination',
        alignment: 82,
        friction: 5,
        urgency: 85,
        trajectory: 'de-escalating',
        sentiment: 'coordinated, responsive',
        recommendation: 'Coordination is stabilizing. Maintain the 15-minute check-in cadence.',
      },
    ],
  },
  {
    id: 'humanitarian-partnership',
    title: 'Humanitarian Partnership Discussion',
    description: 'Two international organizations discuss a joint humanitarian operation. The conversation shifts from alignment to concern over resource allocation.',
    domain: 'Global Organizations',
    languageA: 'en',
    languageB: 'ar',
    participantA: 'Operations Lead',
    participantB: 'Country Director',
    messages: [
      {
        speaker: 'A',
        text: 'I am glad we are aligning on this joint operation. Our organizations have complementary strengths in this region.',
        intent: 'Partnership Building',
        alignment: 75,
        friction: 8,
        urgency: 30,
        trajectory: 'converging',
        sentiment: 'warm, collaborative',
        recommendation: 'Strong foundation. Move toward operational specifics.',
      },
      {
        speaker: 'B',
        text: 'أتفق تماماً. خبرتنا الميدانية وخبرتك اللوجستية يمكن أن تكمل بعضهما البعض بشكل ممتاز.',
        translatedText: 'I completely agree. Our field expertise and your logistical capacity can complement each other excellently.',
        language: 'ar',
        intent: 'Partnership Building',
        alignment: 80,
        friction: 5,
        urgency: 28,
        trajectory: 'converging',
        sentiment: 'enthusiastic, aligned',
        recommendation: 'High alignment. Good moment to introduce operational structure.',
      },
      {
        speaker: 'A',
        text: 'For the first phase, we would lead logistics while your team manages field operations. Budget split would be 60-40.',
        intent: 'Proposal',
        alignment: 70,
        friction: 15,
        urgency: 35,
        trajectory: 'stable',
        sentiment: 'structured, proposing',
        recommendation: 'Watch for reaction to the budget split — this is where alignment may be tested.',
      },
      {
        speaker: 'B',
        text: 'الهيكل مقبول، لكن تقسيم الميزانية يحتاج إلى نقاش. فريقنا يتحمل مخاطر أكبر في الميدان.',
        translatedText: 'The structure is acceptable, but the budget split needs discussion. Our team bears greater risk in the field.',
        language: 'ar',
        intent: 'Unresolved Concern',
        alignment: 50,
        friction: 38,
        urgency: 45,
        trajectory: 'diverging',
        sentiment: 'concerned, advocating',
        intentShift: {
          from: 'Partnership Building',
          to: 'Unresolved Concern',
          description: 'Country Director shifts from enthusiastic alignment to raising concerns about budget fairness — a shift from convergence to unresolved concern.',
          severity: 'medium',
        },
        recommendation: 'Concern raised over risk-reward balance. Acknowledge the field risk before revisiting the budget split.',
      },
      {
        speaker: 'A',
        text: 'You raise a valid point about field risk. What if we adjust to 55-45 and add a risk-adjustment clause for hazardous conditions?',
        intent: 'Concession',
        alignment: 62,
        friction: 22,
        urgency: 38,
        trajectory: 'converging',
        sentiment: 'responsive, adjusting',
        recommendation: 'Good concession. Watch for whether the adjustment is accepted.',
      },
      {
        speaker: 'B',
        text: 'هذا يقترب من العدالة. أقبل بهذا الإطار، وسنناقش التفاصيل التشغيلية في اجتماعنا القادم.',
        translatedText: 'This is closer to fair. I accept this framework, and we will discuss operational details in our next meeting.',
        language: 'ar',
        intent: 'Conditional Agreement',
        alignment: 72,
        friction: 12,
        urgency: 30,
        trajectory: 'converging',
        sentiment: 'satisfied, forward-looking',
        recommendation: 'Agreement reached. Document the framework and schedule the operational planning meeting.',
      },
    ],
  },
]
